NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.orgc.example-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.orgc.example-cert.pem
    OrganizationalUnitIdentifier: peer
